################################################################################
# @file   BufferDisableTopic.srv
# @author Adrian-Stanea (Adrian.Stanea@analog.com)
#
# SPDX-License-Identifier: Apache-2.0 (see LICENSE file)
# Copyright (c) 2025 Analog Devices, Inc.
################################################################################
#
# Description:
#   Disables a topic for a buffer.
#
# Request:
#   device_path (string):
#       - Description: The path to the device.
#   topic (string):
#       - Description: The topic to be disabled.
#
# Response:
#   success (boolean):
#       - Description: Indicates if the operation was successful.
#   message (string):
#       - Description: Provides additional information.
#
################################################################################


string device_path
---
bool success
string message
